export { default as request, setApiBaseUrl, getApiBaseUrl, TOKEN_KEY } from './request';

export {
  getHotSinger,
  getSearchKeyword,
  getHotSearch,
  getPlaylistCategory,
  getRecommendMusic,
  getDayRecommend,
  getNewAlbum,
  getBanners,
  getPersonalizedPlaylist,
  getPersonalFM,
  getPrivateContent,
  getPersonalizedMV,
  getTopAlbum,
  getPersonalizedDJ,
} from './home';

export {
  fmTrash,
  setFmMode,
  getRecommendResource,
  getMusicQualityDetail,
  getMusicUrl,
  getMusicDetail,
  getMusicLrc,
  getParsingMusicUrl,
  likeSong,
  dislikeRecommendedSong,
  getLikedList,
  createPlaylist,
  updatePlaylistTracks,
  getMusicListByType,
  getAlbumDetail,
  getPlaylistDetail,
  subscribePlaylist,
  subscribeAlbum,
  getHistoryRecommendDates,
  getHistoryRecommendSongs,
  getIntelligenceList,
  getPlaylistTrackAll,
  getSongWiki,
  getSongCreators,
  getSongDynamicCover,
  getSongChorus,
  getSongCopyrightRcmd,
  getSongRedCount,
  checkSongLike,
  getSongDownloadUrl,
  matchSongUrl,
  getSheetList,
  getSheetPreview,
} from './music';

export {
  getQrKey,
  createQr,
  checkQr,
  getLoginStatus,
  getLoginUserDetail,
  logout,
  loginByCellphone,
  loginByCaptcha,
  loginByEmail,
  loginByUid,
  registerAnonymous,
  refreshLogin,
  sendCaptcha,
  verifyCaptcha,
} from './login';

export {
  getSearch,
  getSearchSuggestions,
} from './search';

export {
  getUserDetail,
  getUserPlaylist,
  getUserRecord,
  getRecentSongs,
  getRecentPlaylists,
  getRecentAlbums,
  getUserFollows,
  getUserFollowers,
  followUser,
  checkMutualFollow,
  getFollowMixed,
  getUserAccount,
  getUserDetailInfo,
  getUserSubcount,
  getUserLevel,
  getUserBinding,
  getUserMedal,
  getUserEvent,
  getUserDj,
  updateUserInfo,
  getUserSocialStatus,
  getSocialStatusSupport,
  getSocialStatusRcmd,
  editSocialStatus,
  getUserFollowsInfo,
  getUserPlaylists,
  getUserCreatePlaylist,
  getUserCollectPlaylist,
  getUserAlbumSublist,
  getPurchasedAlbumList,
  getPurchasedSongs,
  getArtistNewMv,
  getDjSublist,
  getDjProgram,
  getDjDetail,
  getRecentDj,
  uploadAvatar,
} from './user';

export {
  importPlaylist,
  getImportTaskStatus,
  deletePlaylist,
  updatePlaylistName,
  updatePlaylistDesc,
  updatePlaylistTags,
  updatePlaylistCover,
  updatePlaylist,
  getHotPlaylistCategories,
  getHighqualityTags,
  updatePlaylistOrder,
  getPlaylistSubscribers,
  getPlaylistDetailDynamic,
  updatePlaylistPlaycount,
  getPlaylistRcmd,
} from './playlist';

export {
  getArtistDetail,
  getArtistTopSongs,
  getArtistAlbums,
  getArtistDetailDynamic,
  getArtistDesc,
  getArtistTopSong,
  getArtistSongs,
  getArtistMv,
  getArtistVideo,
  subscribeArtist,
  getArtistSublist,
  getArtistFans,
  getArtistFollowCount,
  getArtistList,
} from './artist';

export {
  getNewAlbums,
} from './album';

export {
  getMusicComment,
  getPlaylistComment,
  getAlbumComment,
  getMvComment,
  getHotComment,
  getFloorComment,
  sendComment,
  likeComment,
  getHotwallComment,
  getUserCommentHistory,
  getEventComment,
  getNewComment,
  getVideoComment,
  getDjComment,
  getCommentInfoList,
  reportComment,
  hugComment,
  getCommentHugList,
} from './comment';

export {
  getTopMv,
  getAllMv,
  getMvDetail,
  getMvUrl,
} from './mv';

export {
  getSimiSong,
  getSimiPlaylist,
  getSimiMv,
  getSimiArtist,
  getSimiUser,
} from './simi';

export {
  getListByTag,
  getListByCat,
  getRecommendList,
  getListDetail,
  getAlbumList,
  getToplist,
} from './list';

export {
  getStyleList,
  getStylePreference,
  getStyleDetail,
  getStyleSong,
  getStyleAlbum,
  getStylePlaylist,
  getStyleArtist,
} from './style';

export {
  searchVoiceList,
  getVoiceList,
  searchVoiceInList,
  getVoiceDetail,
  updateVoiceOrder,
  getVoiceListDetail,
  deleteVoice,
  uploadVoice,
  getVoiceLyric,
  getMyCreatedVoiceList,
} from './voice';

export {
  getFirstListenInfo,
  getAnnualSummary,
  getMusicCalendar,
  getAidjContentRcmd,
  getRadioSport,
  matchAudio,
  getTopArtists,
  getToplistArtist,
  checkMusic,
} from './advanced';
